/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface BackDrop {
        "hideBackdrop": () => Promise<void>;
        "showBackdrop": () => Promise<void>;
        "visible": boolean;
    }
    interface IconAlert {
    }
    interface SlideOver {
        "handleClose": () => Promise<void>;
        "handleTrigger": () => Promise<void>;
        "qaIdClose": string;
        "qaIdElement": string;
        "visible": boolean;
    }
    interface TestIcon {
        "icon": "alert";
        "iconsize": "md";
        "icontype": "text";
        "qaIdElement": string;
    }
}
export interface SlideOverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLSlideOverElement;
}
declare global {
    interface HTMLBackDropElement extends Components.BackDrop, HTMLStencilElement {
    }
    var HTMLBackDropElement: {
        prototype: HTMLBackDropElement;
        new (): HTMLBackDropElement;
    };
    interface HTMLIconAlertElement extends Components.IconAlert, HTMLStencilElement {
    }
    var HTMLIconAlertElement: {
        prototype: HTMLIconAlertElement;
        new (): HTMLIconAlertElement;
    };
    interface HTMLSlideOverElement extends Components.SlideOver, HTMLStencilElement {
    }
    var HTMLSlideOverElement: {
        prototype: HTMLSlideOverElement;
        new (): HTMLSlideOverElement;
    };
    interface HTMLTestIconElement extends Components.TestIcon, HTMLStencilElement {
    }
    var HTMLTestIconElement: {
        prototype: HTMLTestIconElement;
        new (): HTMLTestIconElement;
    };
    interface HTMLElementTagNameMap {
        "back-drop": HTMLBackDropElement;
        "icon-alert": HTMLIconAlertElement;
        "slide-over": HTMLSlideOverElement;
        "test-icon": HTMLTestIconElement;
    }
}
declare namespace LocalJSX {
    interface BackDrop {
        "visible"?: boolean;
    }
    interface IconAlert {
    }
    interface SlideOver {
        "onClose"?: (event: SlideOverCustomEvent<any>) => void;
        "onTrigger"?: (event: SlideOverCustomEvent<any>) => void;
        "qaIdClose"?: string;
        "qaIdElement"?: string;
        "visible"?: boolean;
    }
    interface TestIcon {
        "icon"?: "alert";
        "iconsize"?: "md";
        "icontype"?: "text";
        "qaIdElement"?: string;
    }
    interface IntrinsicElements {
        "back-drop": BackDrop;
        "icon-alert": IconAlert;
        "slide-over": SlideOver;
        "test-icon": TestIcon;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "back-drop": LocalJSX.BackDrop & JSXBase.HTMLAttributes<HTMLBackDropElement>;
            "icon-alert": LocalJSX.IconAlert & JSXBase.HTMLAttributes<HTMLIconAlertElement>;
            "slide-over": LocalJSX.SlideOver & JSXBase.HTMLAttributes<HTMLSlideOverElement>;
            "test-icon": LocalJSX.TestIcon & JSXBase.HTMLAttributes<HTMLTestIconElement>;
        }
    }
}
